// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package logto

type Swagger struct {
	// 1 - Endpoints for the Swagger JSON document.
	JSON *JSON

	sdkConfiguration sdkConfiguration
}

func newSwagger(sdkConfig sdkConfiguration) *Swagger {
	return &Swagger{
		sdkConfiguration: sdkConfig,
		JSON:             newJSON(sdkConfig),
	}
}
