// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/klucherev/logto-go-client/models/components"
)

type DeleteDomainRequest struct {
	// The unique identifier of the domain.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDomainRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteDomainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteDomainResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
