// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/klucherev/logto-go-client/models/components"
)

type DeleteIdentityRequest struct {
	Target string `pathParam:"style=simple,explode=false,name=target"`
}

func (o *DeleteIdentityRequest) GetTarget() string {
	if o == nil {
		return ""
	}
	return o.Target
}

type DeleteIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
