// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/klucherev/logto-go-client/models/components"
)

type DeletePrimaryEmailResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeletePrimaryEmailResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
