// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/klucherev/logto/models/components"
)

type GetWellKnownUserOpenapiJSONResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetWellKnownUserOpenapiJSONResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
