// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/klucherev/logto-go-client/models/components"
)

type GetWellKnownEndpointRequest struct {
	// The unique identifier of the tenant.
	TenantID string `pathParam:"style=simple,explode=false,name=tenantId"`
}

func (o *GetWellKnownEndpointRequest) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

// GetWellKnownEndpointResponseBody - OK
type GetWellKnownEndpointResponseBody struct {
	User string `json:"user"`
}

func (o *GetWellKnownEndpointResponseBody) GetUser() string {
	if o == nil {
		return ""
	}
	return o.User
}

type GetWellKnownEndpointResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *GetWellKnownEndpointResponseBody
}

func (o *GetWellKnownEndpointResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWellKnownEndpointResponse) GetObject() *GetWellKnownEndpointResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
