// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/klucherev/logto-go-client/models/components"
)

type UpdatePasswordRequest struct {
	// The new password for the user.
	Password string `json:"password"`
}

func (o *UpdatePasswordRequest) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

type UpdatePasswordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *UpdatePasswordResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
